### ISSUE TITLE
Implement missing option on createI18n

### ISSUE THREAD

**Issue by staaph** [therealcoder1337/vue-i18n-pico#3]
optional missing handler to handle unknown keys. Reference to https://vue-i18n.intlify.dev/api/composition.html#missing
automatic console warning in development 'key {xy} is unknown. using fallback {fallback}'

**Comment by therealcoder1337** [comment]
This can be handled by using a plugin, once the API is finished. I.e. (subject to change):

```ts
const plugin = (args: TranslatePluginArgs) => {
  if (!args.result) {
    console.warn(`missing translation for "${args.name}"`);
  }
};
```
